### ISSUE TITLE
How to avoid Safari's "Do you want to allow this page to open <app>?" in macOS

### ISSUE THREAD

**Issue by danielmartinprieto** [openid/AppAuth-iOS#113]
As I couldn't make the http listener work (see https://github.com/openid/AppAuth-iOS/issues/107), I've implemented the AppAuth integration in my macOS app using a custom URL scheme. 

Does anyone know if it's possible to avoid Safari showing the message "Do you want to allow this page to open <app>?" when the redirect URL of an authorisation request opens the app to continue with authentication flow?

I've tried to find a way but it seems it's not possible. Thanks!

**Comment by WilliamDenniss** [comment]
You can use a loopback redirect, rather than a custom URI scheme. There won't be a dialog for the loopback redirect.

There's an example of this in the macOS sample. Button is named `Authorize (HTTP Redirect, auto)`

Code is here:
https://github.com/openid/AppAuth-iOS/blob/master/Examples/Example-macOS/Source/AppAuthExampleViewController.m#L239

**Comment by danielmartinprieto** [comment]
Yeah, I tried, but had this problem that I couldn't solve: https://github.com/openid/AppAuth-iOS/issues/107, so I had to use a custom URL scheme. Thanks, anyway.
