### ISSUE TITLE
Unable to authorize 

### ISSUE THREAD

**Issue by ShailendraGangwar** [openid/AppAuth-iOS#123]
Hi,

I am trying to build a new project. I have imported all the files asked but I am getting error.

*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '+[OIDAuthState authStateByPresentingAuthorizationRequest:presentingViewController:callback:]: unrecognized selector sent to class 0x10a6eec30'

Please help me.

**Comment by zboralski** [comment]
@ShailendraGangwar try adding -fObjC to Other Linker Flags (ref: [Building Objective-C static libraries with categories](https://developer.apple.com/library/content/qa/qa1490/_index.html))

**Comment by ShailendraGangwar** [comment]
Thanks!
I missed that part.

I have one more question. I am now able to authenticate the account, but i dont see terms of use screen. I see consent screen then i click on account and get back to application without showing terms of use screen. 

Do you have anything on this?

**Comment by zboralski** [comment]
@ShailendraGangwar maybe you have already authorised your client?

**Comment by ratkins** [comment]
For anyone else seeing this issue: we *did* add `-ObjC` in `OTHER_LINKER_FLAGS` but that didn't fix the problem (and turned out to not be needed anyway)—we'd included both `AppAuth.framework` and `AppAuthCore.framework` in the app target's "Linked frameworks and libraries". This is unnecessary, only `AppAuth.framework` needs to be added there (and in the associated `carthage copy-frameworks` script.)

**Comment by tethridge** [comment]
If you happen to stumble across this post because you are seeing this error when trying spm4kmp, then the fix is to not use the "copydependenciestoapp".  Instead add the exported local repository.
