### ISSUE TITLE
Alternative to exception handling in case of incorrect authorization state

### ISSUE THREAD

**Issue by eli-symbolab** [openid/AppAuth-iOS#136]
Hi --
I'm using AuthApp to get an authorization code from Microsoft Office365. After starting an authentication flow with AppAuth, the user is presented with a Safari control. If the they hit "Done" on the window before auth flow has completed, the application is still opened via `openURL:`, and we call `resumeAuthorizationFlowWithURL:` immediately after. This throws an `OIDOAuthExceptionInvalidAuthorizationFlow`.

I can easily catch this with `@try`/`@catch` but it would be nice to have an alternative to using exceptions in normal flow control. This could be accomplished by changing the exception flow to returning a result object, adding an `NSError` out param, or allowing an external state test before calling `resumeAuthorizationFlowWithURL:`. Alternatively it could fail silently and return `NO`.

Thanks for your time. I'd be happy to implement any of these if it sounds like a good idea.

**Comment by StevenEWright** [comment]
@WilliamDenniss Is this the correct label? We have been pretty good about only using exceptions to represent developer errors, and errors to represent unexpected (or recoverable) runtime errors. Should the OP have known not to call `resumeAuthorizationFlowWithURL:` ? If so, I'd be a proponent of keeping the exception and not using an error as an alternative. Curious if you know of some background related to Office365 / Microsoft's O.P. which would make the current approach unworkable?

**Comment by eli-symbolab** [comment]
Hi @StevenEWright, thanks for the attention.
I was under the impression that this is due to how Safari handles tapping the "Done" arrow, rather than anything specific about Microsoft. Is there a flag I can check to see if the Safari task completed successfully or not? Otherwise the app seems to have no knowledge of the auth state and continues on its way.

**Comment by julienbodet** [comment]
After reading this issue, I agree with @StevenEWright approach and I think the OP should have known not to call `resumeAuthorizationFlowWithURL:`. 

At the time this issue was raised there was no way to check if the user cancelled the authorization flow by closing the `SFSafariViewController` because of issue #221. @eli-symbolab, now this is fixed and you can check for `OIDErrorCodeUserCanceledAuthorizationFlow` in the `OIDAuthStateAuthorizationCallback` and then assign nil to your AppDelegate's `OIDAuthorizationFlowSession` property based on that. But I think this property should also be set to nil for any other authorization error, avoiding to call `resumeAuthorizationFlowWithURL:` if the authorization has failed.

Knowing that, I don't think returning an `NSError` is still necessary, what do you think @WilliamDenniss?

**Comment by eli-symbolab** [comment]
Thank you @julienbodet. I have found the new error code constant.

So the detail I missed was that if the callback returns a nil `authorizationResponse`, I should set the flow session to nil as well?

I tried to reproduce the original problem and was unable to ... maybe pressing Done no longer triggers the `openURL` method of the `AppDelegate`? At any rate the behavior in iOS 11 seems to avoid calling `openURL` entirely.
