### ISSUE TITLE
Getting the raw token

### ISSUE THREAD

**Issue by atomicbird** [openid/AppAuth-iOS#154]
I'm using AppAuth on iOS, and I need to get the raw token string so that I can use it to make IMAP calls to Gmail.

* `OIDTokenResponse.h` indicates that this is in `accessToken`, but only if the `response_type` includes `token`. However...
* If the `response_type` includes `token`, `OIDAuthorizationRequest` asserts because this type is not supported. **However**...
* Even with a supported response type, `accessToken` is not nil after authentication. ***However***...
* The IMAP server rejects this value.

This is all pretty confusing. It's documented that I can't get a token the way I'm authenticating, but I can't use the documented way because it's unsupported. But I get one anyway, only it doesn't work. Can anyone point me in the right direction?

**Comment by atomicbird** [comment]
It looks like my last point was a question of using the right scope. Once I fixed that, the IMAP server accepted the token.

I'd appreciate it if someone could clarify the previous points, though. As I read it, I can't get a token with a `response_type` of `OIDResponseTypeCode`, except that I **do** get one, which is good because the documented way to get one is also documented to not work. So while I have apparently-working code right now I can't help worry that I'm dancing on thin ice here with catastrophe looming in the near future.

**Comment by WilliamDenniss** [comment]
There's a bug in the docs. `OIDTokenResponse` should always contain an access token when using the code flow (either resulting from the code exchange or refresh) for non-error cases.

That said, rather than worrying about the low-level protocol details, I recommend using OIDAuthState to get fresh tokens for API calls, in particular with [performActionWithFreshTokens](https://github.com/openid/AppAuth-iOS/#making-api-calls). The README has a complete sample of this approach.

**Comment by atomicbird** [comment]
Thanks!
