### ISSUE TITLE
Prevent the use of SFAuthenticationSession?

### ISSUE THREAD

**Issue by borgeser** [openid/AppAuth-iOS#182]
Hi,

I'm creating an app with a lot of webviews (I use `SFSafariViewController`). I need to share the cookies between the authentication controller provided by the app and my instances of `SFSafariViewController`.

Everything works well on iOS9 and iOS10 but in iOS11 the library is using `SFAuthenticationSession`. I understand the purpose of this class but this class forbids the sharing of cookies in my app.

I'd like to know if there is a way to prevent using `SFAuthenticationSession` in the library. Or maybe if there is another way to achieve my wish: sharing cookies between the authentication process and my `SFSafariViewController`s.

Thanks.

**Comment by WilliamDenniss** [comment]
Hey,

In your case, I agree that your best bet will be to use `SFSafariViewController` as you suggest. You'll lose SSO with Safari, but gain it within your app.

AppAuth doesn't currently support this directly, as we assumed everyone wants SSO with Safari. It's trivial to hack the code, you can just delete these lines: https://github.com/openid/AppAuth-iOS/blob/83736c9a3f658bea63be9164e37d0be54d0240a5/Source/iOS/OIDAuthorizationUICoordinatorIOS.m#L91-L110

Here's what I'd recommend: clone AppAuth into your project, e.g. `./ThirdParty/AppAuth-iOS/`. Delete the code I highlighted above. If you're using Pods, simply add `pod 'AppAuth', :path => 'ThirdParty/AppAuth-iOS/'`. That way the pod is included and built from your local fork.

We could add support to AppAuth, but first I would want to validate that a lot of people have this same use-case. Otherwise, I think it's pretty easy for you to customize how you like as a once-off.

What do you think?

William

**Comment by hudeldudel** [comment]
I would also love to see an option to prevent the use auf SFAuthenticationSession.
In our case, app stakeholders don't like the system message for our 1st party apps. They prefer to loose shared state over having the SFAuthenticationSession privacy message.

**Comment by borgeser** [comment]
Hi William and sorry for the delay,

That is what I've done first, except I didn't want to fork the library so I've just created in my project a custom implementation of OIDAuthorizationUICoordinator. @hudeldudel I recommend you to do that.

But finally SafariViewController wasn't enough because I have also WKWebiews in my app. So I've created another implementation of OIDAuthorizationUICoordinator which only uses WKWebviews.
My work was rather similar to these commits:
https://github.com/equinux/AppAuth-iOS/commit/13d034c6f252f9a802ee684640a98fd371703157
https://github.com/equinux/AppAuth-iOS/commit/0c55315c9e8e3b09f79633043f5f69d7271bead2

Thanks for your help.

**Comment by julienbodet** [comment]
I also need to prevent the use of `SFAuthentificationSession`. Once logged in I want to be able to open a `SFSafariViewController` using the session cookies from the login. `SFSafariViewController` shares its cookies between multiple instances in the app.

**Comment by WilliamDenniss** [comment]
Good call @borgeser, a custom `OIDAuthorizationUICoordinator` is definitely what you want to do.

What I should have recommended rather than forking was to make a copy of the OIDAuthorizationUICoordinatorIOS.h/.m class, and then tweak it as you need. #200 has a code sample of doing an authorization with a non-default UI coordinator.

@julienbodet you can use this technique – just create your own `OIDAuthorizationUICoordinator`, optionally using one of the existing implementations as a starting point.

**Comment by ANGOmarcello** [comment]
I need this option as well. To add my opinion on this:
Monkey Patching is always a bad idea, because you lose the ability to update and move fast. So if this would be an included option it would be very great.

**Comment by bavarskis** [comment]
I would love this too. I forked the AppAuth and removed the unnecessary lines, but that spells trouble, I'd be much better just to have it out of the box.
