### ISSUE TITLE
possible to bypass the SSL Validation in iOS ?

### ISSUE THREAD

**Issue by Karthikeyan1108** [openid/AppAuth-iOS#189]
In certain debug environments, there is a need to disable SSL cert and host verification. App auth currently does not expose a way to alter the **Nsurlsession** to do this.Please help !

**Comment by WilliamDenniss** [comment]
So basically a way to expose NSURLSession for customization.

It doesn't seem like this is a high priority feature, if you or anyone would like to file a PR with a well thought out implementation for how to expose the necessary bits for customization I'd review it.

Until then, AppAuth is pretty easy to fork and modify as you need, so that's what I'd recommend for a once-off to satisfy your development requirement. The included examples show how to reference AppAuth as a development Pod allowing you to easily make chances to your personal fork.

**Comment by WilliamDenniss** [comment]
This should be possible using the feature introduced in #137. Use the NSURLSession customization to tweak the SSL handling as you need.
