### ISSUE TITLE
More than just `performActionWithFreshTokens`?

### ISSUE THREAD

**Issue by atomicbird** [openid/AppAuth-iOS#204]
I'm having a problem getting current tokens when my app has been running for a long time.

To ensure that I have current tokens, I do the following:

* Wrap all of my OAuth-requiring server calls in `performActionWithFreshTokens`
* Ensure that whenever I need to give the server a token, I get it from `authState.lastTokenResponse.accessToken`.

This works fine at first. The token is good for an hour, and when the hour rolls over I have a fresh token and server calls keep working. At some later time (say when the app has been running 2-3 hours?) this doesn't work any more and the server complains that the token is no longer valid.

When this happens, `performActionWithFreshTokens` continues to return an access token and a nil error parameter.

Should I not be using `authState.lastTokenResponse.accessToken` here? I'm trying some alternatives but it takes several hours to reproduce the problem and I'm hoping someone will be able to help out.

**Comment by shashank109** [comment]
I am facing similar kind of issue. When I call performActionWithFreshTokens, only sometime it gives me me the callback with token and most of the times it doesn't even give the callback or response.

**Comment by atomicbird** [comment]
That sounds like something different from what I'm seeing. For me the callback always occurs.

**Comment by WilliamDenniss** [comment]
@shashank109 this does seem different, please open a new issue if needed.

@atomicbird the only explanation I have for the behavior you're observing is that OIDAuthState continues to think the token is valid. That logic is here:

https://github.com/openid/AppAuth-iOS/blob/5d321b83d8b8cd64068c774cf2377d69a61b23a3/Source/OIDAuthState.m#L519-L533

Two things to check next time you can repro this: 
1/ is there an expiry time? AppAuth will assume if there isn't that it's always valid.
2/ is the expiry date correct? i.e. is it not way in the future?

AppAuth doesn't have insight into your API calls or responses (since they are outside of the purview of OAuth), hence we can't directly catch and correct this issue. However if you are getting an error that indicates the token needs refreshing, one action you could take would be to call `setNeedsTokenRefresh` on the OIDAuthState, then try the API call again. `setNeedsTokenRefresh` forces the refresh to occur regardless of whether AppAuth thinks the existing token is fresh or not. I suspect if you do this it should fully mitigate the issue with no noticeable user impact.

https://github.com/openid/AppAuth-iOS/blob/5d321b83d8b8cd64068c774cf2377d69a61b23a3/Source/OIDAuthState.h#L252-L255

**Comment by atomicbird** [comment]
@WilliamDenniss Thanks for the info. While debugging this, I have a timer that makes a server call once per minute, using `performActionWithFreshTokens`. In the callback after refreshing, I log the access token and the expiration time.

I'm using Gmail via IMAP, and the tokens expire after an hour. The expiration times look right-- initially an hour in the future and gradually counting down. Shortly before expiration I get a new token with a new expiration time.

What's odd is that the first call with this new token succeeds, but the next call a minute later fails.

I'll experiment with `setNeedsTokenRefresh` and report back. I'll also look into [MailCore](https://github.com/MailCore/mailcore2), which is where I'm using the tokens, to see if it might be unexpectedly caching an old value.

**Comment by atomicbird** [comment]
@WilliamDenniss It turns out that this was a problem of MailCore unexpectedly caching old tokens (apparently just giving it a new token isn't enough, but [that's another story](https://github.com/MailCore/mailcore2/issues/1714)). Refreshed tokens work better if you actually use them.

**Comment by WilliamDenniss** [comment]
Thanks for the update @atomicbird! Let us know if anything needs to be changed on the AppAuth side in the future.
