### ISSUE TITLE
client_secret_basic header value invalid when special characters are used

### ISSUE THREAD

**Issue by panva** [openid/AppAuth-iOS#233]
According to https://tools.ietf.org/html/rfc6749#section-2.3.1 (+appendix) the client_id and client_secret values are to be `application/x-www-form-urlencoded`-encoded before being used the basic authentication scheme as username and password. This is [currently not the case](https://github.com/openid/AppAuth-iOS/blob/0.92.0/Source/OIDTokenRequest.m#L277-L282).

Given a client_id value of `1PpG/Q 1` and client_secret value of `z/tZ9VwFZqApmIQ+ZH1I5pLk/uB4ud:X2/8bL+wfFTt1rFw=` the Authorization header should be processed as follows

```
// Authorization: Basic base64(formEncode(1PpG/Q 1):formEncode(z/tZ9VwFZqApmIQ+ZH1I5pLk/uB4ud:X2/8bL+wfFTt1rFw=))

// Authorization: Basic base64(1PpG%2FQ+1:z%2FtZ9VwFZqApmIQ%2BZH1I5pLk%2FuB4ud%3AX2%2F8bL%2BwfFTt1rFw%3D)

Authorization: Basic MVBwRyUyRlErMTp6JTJGdFo5VndGWnFBcG1JUSUyQlpIMUk1cExrJTJGdUI0dWQlM0FYMiUyRjhiTCUyQndmRlR0MXJGdyUzRA==
```

This is very likely to cause issues with clients using this scheme with a provider that also omits this requirement and has identifier or a secret with special characters.

**Comment by WilliamDenniss** [comment]
Agree this is a bug.

Deep links:
OAuth2-flavored form-urlencoded: https://tools.ietf.org/html/rfc6749#appendix-B
Referenced spec: https://www.w3.org/TR/1999/REC-html401-19991224/interact/forms.html#h-17.13.4.1

We can do something like: https://github.com/openid/AppAuth-iOS/blob/d27db29ce26cf1d1c390034e94b00d44af3da750/Source/OIDURLQueryComponent.m#L132 just need to specify the right set of reserved characters.

My advise would be to percent encode space, rather than as "+" as it's a valid encoding, and less ambiguous (and we don't need the "+"-encoding for aesthetic reasons).

**Comment by panva** [comment]
> My advise would be to percent encode space

As seen by the example in appendix b, that's the way to go.
