### ISSUE TITLE
AppAuth lib issue using SFAuthenticationSession 

### ISSUE THREAD

**Issue by nanumonu** [openid/AppAuth-iOS#278]
@WilliamDenniss 
In AppAuth lib since its using SFAuthenticationSession and opening in browser. Do we have any way to open directly into the application if the application is already installed into the device rather then going to any browser ??

**Comment by WilliamDenniss** [comment]
Yes, it's easy. Replace this:
https://github.com/openid/AppAuth-iOS/blob/b4ca39a38f0d991bd17c56ebd01756a41da54061/Examples/Example-iOS_Swift-Carthage/Source/AppAuthExampleViewController.swift#L394

With this:

```swift
let agent = OIDExternalUserAgentIOSCustomBrowser.customBrowserSafari()
appDelegate.currentAuthorizationFlow = OIDAuthState.authState(byPresenting: request, externalUserAgent: agent) { authState, error in
```

That's it!

This works because the Safari external user agent just uses `openURL` so if you use a custom URI scheme in your request rather than "https", it will open the other app instead of Safari.

Make sure your redirect URI scheme is registered in your bundle as normal (per the [instructions](https://github.com/openid/AppAuth-iOS/blob/master/Examples/Example-iOS_Swift-Carthage/README.md) in the sample). **Of course, the app which is serving the OAuth request must on completion call openURL with a valid OAuth 2.0 authorization response.** .

Good luck with your project.

**Comment by nanumonu** [comment]
@WilliamDenniss 

Thanks for your reply 
now issue is its going into app but within seconds it goes to webpage and opens redirect url why is it so ??

**Comment by WilliamDenniss** [comment]
I can't really help much further on this, as it's specific to your own situation. I'd suggest contacting the owner of the app.

I can tell you that broadly this is possible in AppAuth. An app can act as an external user-agent and support RFC 8252-style flows.

**Comment by nanumonu** [comment]
oh okay Thank you but after making changes as you suggested did you expect that once it will go into the app and then suddenly will go into safari?? is that was expected result ??

**Comment by WilliamDenniss** [comment]
The request loaded in the app, that behavior is expected so AppAuth is behaving as intended here. After that point it's no longer in the control of AppAuth.

What happened next (like that app then opening Safari) was entirely governed by the logic in the app, not anything to do with AppAuth or iOS.

**Comment by nanumonu** [comment]
@WilliamDenniss 
Thanks

i do notice once i change to
 appDelegate.currentAuthorizationFlow = OIDAuthState.authState(byPresenting: request, externalUserAgent: agent) { authState, error in
as you suggested and now i am not getting token but if i replace that with appDelegate.currentAuthorizationFlow = OIDAuthState.authState(byPresenting: request, presenting: self) { authState, error in i am getting token

**Comment by WilliamDenniss** [comment]
For some reason your app is not receiving the redirect URI. It could be that your app didn't register for the custom URI scheme correctly, that the external user-agent you used is not sending the redirect using `openURL`, or that the authorization server isn't sending it at all.

You could rule out some of these problems by trying the flow in an external user-agent that is known to work correctly, like Chrome. Install Chrome for iOS and try using it as your external user agent.
```swift
let agent = OIDExternalUserAgentIOSCustomBrowser.customBrowserChome()
``
The return path is exactly the same for Chrome, and any other app-based external user-agent you use – so if it works with Chrome, then the bug is in that other external user-agent or something related to it. If it _doesn't_ work in Chrome, then the bug is in your app (you're not getting the redirect correctly), or in the authorization server (it's not sending the redirect correctly).
