### ISSUE TITLE
Support for private_key_jwt auth, signed request objects, verifying id tokens/c_hash, etc

### ISSUE THREAD

**Issue by jogu** [openid/AppAuth-iOS#290]
Hi,

I'm working on a project that involves mobile clients that are dynamically registered confidential clients using private_key_jwt authentication, keeping their keys in the Secure Enclave, etc - really aiming towards OpenID FAPI part 2 compliance. AppAuth doesn't currently support much of this.

I'm hence wondering about a few things that I've not seen discussed anywhere so far:

1) What kind of appetite is there to add things like the above inside AppAuth? (It is basically possible to do all that without making changes to AppAuth, though it has certainly been awkward in places.)

2) AppAuth-iOS seems to have a zero dependencies policy; that certainly makes sense at the moment but would something like pulling in a JWT/JWS/JWK library be acceptable to get these extra features? (Or perhaps it may mean creating such a library - I think Google have an initiative going on to create JWT libraries, anyone know if that covers iOS/ObjC/Swift?)

3) Slightly related to '2', but if there's a definite desire to keep dependencies to a minimum then I think some built in iOS functionality that makes things easier/possible is only available from iOS 10.0 and in some cases I believe buggy until 10.3. Trying to keep iOS 7 compatibility (which I believe is the current AppAuth aim?) would require quite a bit of extra work that I'm not sure would be justified.

4) Would at least a first cut focussing on ES256 make sense? (Mostly because the Secure Enclave in iOS only supports elliptical keys.)

5) Is there a rule against using swift in AppAuth? It seems like there probably is but I'm not sure I've seen it written anywhere, or if any such rule could be revisited now Apple seem to have having success achieving at source compatibility for swift between Xcode revisions.

(I'm not sure I have time to actually try and do all of this, but there might be bits I can contribute if I know they are wanted and what form they would need to take!)

Apologies that the above is quite long!

Thanks

Joseph

**Comment by WilliamDenniss** [comment]
AppAuth has zero dependencies, which is very much desirable and by design. It makes it so much easier to use by developers. I would be against introducing a mandatory dependency unless it was necessary for a function used by all users of the library. AppAuth itself is a dependency of several other projects, which is another reason to keep it at zero. 

How important is pre-iOS 10.3 support? iOS users upgrade at a pretty rapid pace after all, and even the iPhone 5S can run iOS 12! Personally I'd go with OS functions where possible.

AppAuth is a swift-compatible, Objective-C project for now. There shouldn't be any swift code in the library, but also everything should work fine in Swift (we have Swift samples, and include Swift testing in the CI).

My preference would be to make AppAuth easy to use with such a setup, even if that code wasn't in the base AppAuth library. E.g. you could have a separate open source module that provided this functionality (in Swift, if you wanted!). One of the goals of AppAuth is extensibility – you can see this in multiple places, for example the "additionalParameters" pattern which makes it possible to add support for new specifications like OAuth 2.0 Incremental Authorization without changing the core library.

You mention "It is basically possible to do all that without making changes to AppAuth" which is awesome and certainly our goal, "though it has certainly been awkward in places" – to which I'd encourage you to file bugs that document where extension points are lacking for your use-cases, and PRs to improve the situation.

AppAuth is a community project, typically the people who need the features are the ones who contribute them (as was the case with dynamic registration & logout).

**Comment by jogu** [comment]
Thanks William! That's all very useful info and helps me understand the context.

> You mention "It is basically possible to do all that without making changes to AppAuth" which is awesome and certainly our goal, "though it has certainly been awkward in places" – to which I'd encourage you to file bugs that document where extension points are lacking for your use-cases, and PRs to improve the situation.

I have already filed two PRs though I've not had any comments back on them yet :-)

I've also just filed https://github.com/openid/AppAuth-iOS/issues/292, if you're okay with my suggested approach there I should be able to open a pull request for that too.


With those sorted, the main pain point for app developers trying to do this looks to be JWS signing and verification, and in particular converting private/public keys between Apple's CommonCrypto and JWK. (I've currently ended up with a horrible mishmash of pulling in multiple open source libraries that solve various different parts of that problem as the team I'm working with needed a proof of concept in a huge hurry...)

**Comment by WilliamDenniss** [comment]
Closing this as resolved, now that the FAPI use-case is [unblocked](https://github.com/openid/AppAuth-iOS/issues/292#issuecomment-426251476).

AppAuth now enables developers to use the hybrid flow for use-cases like FAPI, and all the primitives are there, you just need to BYO token verification.

Thanks @jogu for working to improve the coverage here!
