### ISSUE TITLE
Browser Title Bar method?

### ISSUE THREAD

**Issue by mookie5dc** [openid/AppAuth-iOS#31]
I noticed from the answers in this question on the android library(https://github.com/openid/AppAuth-Android/issues/71) that the use of urn:ietf:wg:oauth:2.0:oob is a hack.  Does this library support the browser title bar method at all?  I'm trying to use the MSGraph API and unfortunately, their app registration forces you to use that for the redirect uri and doesn't allow you to change it to a reverse dns format.  Is there a possibility to retrieve the auth code via the browser title bar method with this library?

**Comment by WilliamDenniss** [comment]
The browser title bar cannot be read from `SFSafariViewController` or mobile Safari.

Here is how I would support an OAuth provider who cannot redirect to a custom URI scheme on iOS:

1. Register a universal link, claimed by your app, as the redirect URI at the authorization server, say `https://example.com/oauth2redirect`.  For iOS 9+ users, they will get the authorization response directly in your app (since your app has claimed the link) – and you just pipe the URL into `OIDAuthorizationFlowSession::resumeAuthorizationFlowWithURL`, and you're done.
2. If you need to support iOS 8 and below, then what you can do is as a fall back, actually implement the endpoint `https://example.com/oauth2redirect?<query>` on you server, where all it does is a 302 redirect to `com.example.app:/oauth2redirect?<query>` (preserving the query string).  Your app gets the URL, which you pipe into `resumeAuthorizationFlowWithURL` as with the universal link.

In this way, all your iOS users can receive the redirect. Those on iOS 9 are just a little more secure as the browser will send the response directly to your app (and only your app). On iOS 8, users will load your server's endpoint in the browser, which redirects them to the custom URI scheme – two entry points to your app for receiving the authorization code, same end result.

The only way to hack AppAuth to use `urn:ietf:wg:oauth:2.0:oob` (which I don't recommend) would be to present the authorization request in a `UIWebView`, which allows for inspection of the HTML and retrieval of the code. This is technically possible, but it goes against the recommendations of [OAuth 2.0 for Native Apps](https://tools.ietf.org/html/draft-ietf-oauth-native-apps) for both usability and security reasons, which is why we don't support it.

**Comment by mookie5dc** [comment]
Thanks @WilliamDenniss!  I like that approach and I'm going to do just that.  I assume it would be a similar pattern on android (using the android library)

**Comment by WilliamDenniss** [comment]
Yes, same pattern for Android.

Great! Please let us know how it goes.

**Comment by mookie5dc** [comment]
This sort of works, a few additional questions.

1) when the custom uri is used(non universal link), the redirect uri didn't match when I passed the custom uri into resumeAuthorizationFlowWithURL.  I ended up overriding it back to the universal link version

2) can I use this if a provider is not using PKCE?  I added nonce to the additional parameter hash, but wasn't sure how to use response mode query to get the token since I am doing the redirect.  the discovery url is https://login.microsoftonline.com/common/.well-known/openid-configuration.

Thanks

**Comment by guidedways** [comment]
Not sure if my question is related to @mookie5dc, but I'm trying to use AppAuth with Outlook OAuth2 authentication. They claim to support Native apps however the only redirect URL they support is `urn:ietf:wg:oauth:2.0:oob` :( The auth-flow itself works to the point where the browser can not longer auto-close and return the calling app. I tried adding a custom URL scheme and using that as a redirect_url however in such a case Microsoft's authentication webpage complains the redirect_url is invalid and the only valid URI is `urn:ietf:wg:oauth:2.0:oob`.

Is there no solution to this? Can someone explain what 'hack' needs to be placed into AppAuth to support this? Yahoo has a similar issue with OAuth2 I believe and sadly other than Gmail I can't get AppAuth to work other popular providers (such as Microsoft's Outlook / Live). Thanks.
