### ISSUE TITLE
Authenticating via mod_auth_openidc oauth20

### ISSUE THREAD

**Issue by jeffemandel** [openid/AppAuth-iOS#339]
I'm trying to secure an tomcat servlet for calls from my iOS app with mod_auth_openidc and Gluu 3.1.3. I've used the example code and believe I have a proper access_token. I now want to present that token to mod_auth_openidc via oauth20. I pass this to a request:
` 
        NSString *myTokenString = [NSString stringWithFormat:@"Bearer %@", accessToken];
        [request setValue:myTokenString forHTTPHeaderField:@"Authorization"];
        [request setHTTPMethod:@"GET"];
`

I have mod_auth_openidc configured:
`
                OIDCOAuthIntrospectionEndpointMethod POST
		OIDCOAuthAcceptTokenAs header post
		OIDCOAuthIntrospectionEndpoint https://gluu.example.org/oxauth/restv1/introspection
		OIDCOAuthIntrospectionEndpointParams token_type_hint=access_token

		<Location "/iosendo">
			Require valid-user
			AuthType oauth20
			LogLevel debug
		</Location>
`
Looking at apache2/error.log, I can see that the token is found:
`oidc_oauth_get_bearer_token: bearer token: a1db4edb-b49e-4b58-aad5-e75102120fbf`

and gets passed out to my introspection endpoint:
`
oidc_util_http_form_encoded_data: data=token_type_hint=access_token&token=a1db4edb-b49e-4b58-aad5-e75102120fbf
`

This fails. I've got a thread going over at Gluu, and may start one at mod_auth_openidc, but if you can give me an idea of what I'm doing wrong, I'd appreciate it.

**Comment by WilliamDenniss** [comment]
It looks like you've used AppAuth successfully to obtain the token, and are sending it to the server (protected resource). I'm not sure how much help we can be diagnosing an issue with the protected resource.

FYI, instead of setting the Authorization header manually you can use this method: https://github.com/openid/AppAuth-iOS/blob/0c822671e56cedf159a6d27ccf0669b689c0f2b5/Examples/Example-iOS_ObjC/Source/AppAuthExampleViewController.m#L371 but manual should be fine too.
