### ISSUE TITLE
Automatically login after logout.

### ISSUE THREAD

**Issue by balkarov** [openid/AppAuth-iOS#390]
- OS: iOS
 - Version 12

Hello. Thank you for your library!
My problem in my app:
1) User click button -> opens `SFAuthenticationSession` -> user login
2) User click logout button and app clears cookies
```swift
HTTPCookieStorage.shared.cookies?.forEach(HTTPCookieStorage.shared.deleteCookie)
        URLCache.shared.removeAllCachedResponses()

        WKWebsiteDataStore.default().fetchDataRecords(ofTypes: WKWebsiteDataStore.allWebsiteDataTypes()) { records in
            records.forEach { record in
                WKWebsiteDataStore.default().removeData(ofTypes: record.dataTypes, for: [record], completionHandler: { })
            }
        }
```
3) User click login button -> opens `SFAuthenticationSession` -> user automatically login. 

BUT: if user logout and restarts app he can login again not automatically. 

How to fully logout from app?

**Comment by Tanjchy3** [comment]
I have the same problem.  User clicked logout button - app cleared all cookies and executes [self setAuthState:nil], but when user clicks login button again he gets automatically logged in.

**Comment by WilliamDenniss** [comment]
SFAuthenticationSession uses the cookies from Safari. Your code snippit using `HTTPCookieStorage` and `WKWebsiteDataStore` doesn't clear cookies from Safari. To remove the cookies in Safari, the website that created the cookie can delete it (what normally happens when you sign out of the website), or the user can clear them in Safari's settings.

So the login cookie remains in Safari, and the user can use that to sign-in to your app again. This is basically how Single Sign-on (SSO) works, so if this is not desirable for you then you will need to not use Single Sign-on with AppAuth (e.g. by using the SFSafariViewController approach, see [this answer](https://github.com/openid/AppAuth-iOS/issues/209#issuecomment-404353236)).

**Comment by balkarov** [comment]
@WilliamDenniss how you explain me that when I restart app user does not login automatically?

**Comment by balkarov** [comment]
@WilliamDenniss  ping

**Comment by devkantiwal11** [comment]
@balkarov I am also facing the same issue
case:
1: user login by enter creds
2: user restart the app just after logging in .
3: Now if user login again after logout can see the fields for enter creds .
if user skip step 2 it automatically logged user in
