### ISSUE TITLE
Percent-encoding algorithm used in AppAuth-iOS is not correct

### ISSUE THREAD

**Issue by mkujalowicz** [openid/AppAuth-iOS#48]
Algorithm of encoding characters in the AppAuth-iOS library is not compatible with the "application/x-www-form-urlencoded" type. It leads to different issues in the OAuth2 flow where tokens, authorization codes passed to the server contain special characters.
### Detailed description:

The "application/x-www-form-urlencoded" type is based on special URI percent-encoding rules:
[Wikipedia](https://en.wikipedia.org/wiki/Percent-encoding#The_application.2Fx-www-form-urlencoded_type)

The biggest difference from standard URI encoding is with replacing spaces with the plus sign character "+". Unfortunately standard iOS APIs like:
[NSCharacterSet URLQueryAllowedCharacterSet]
or
NSURLComponents
don't obey these rules. They don't encode the plus sign "+" which is replaced with space afterwards on the server.

Moreover, current implementation of NSURLComponents (iOS 8+)  in the library is wrong. Instead of using [NSURLComponents percentEncodedQuery] it uses [NSURLComponents query] instead, which doesn't encode data at all
https://github.com/openid/AppAuth-iOS/blob/master/Source/OIDURLQueryComponent.m#L166

I've created a branch where both methods (iOS8+ and legacy) are replaced with one NSCharacterSet-based method with custom allowed characters:
https://github.com/mkujalowicz/AppAuth-iOS/tree/url_encoding

I'm using a set of allowed characters similar to what Java URL Encoder has:
https://docs.oracle.com/javase/7/docs/api/java/net/URLEncoder.html
or Ruby:

``` ruby
characters=(0..0x7f).select {|val| URI.encode_www_form([["name", "#{val.chr}"]])  == "name=#{val.chr}"}.inject ("") { |result, object| result + object.chr }
```

I also added a unit test where the encoding can be verified against mentioned rule. I can submit a pull request if you agree with this change. I've also created a Swift playground where you can test all methods:
https://gist.github.com/mkujalowicz/3903fd7efd695864eca606ccc12e097e
(requires Swift 3)

**Comment by WilliamDenniss** [comment]
Thanks for the report. Would be great to get your pull request! Can you sign the CLA for contributing to the OpenID Foundation codebase?  https://github.com/openid/AppAuth-iOS/blob/master/CONTRIBUTING.md

**Comment by mkujalowicz** [comment]
Of course, I'll try to carry out this fast

**Comment by WilliamDenniss** [comment]
Thanks for the great bug report.

I've filed pull request #54 to address the two issues that you raised:

1. On iOS 8+, `OIDURLQueryComponent.URLEncodedParameters` wasn't actually encoding the parameters 😱
2. The `+` character is ambiguous as it decodes to space with `application/x-www-form-urlencoded` processing.

Rather than encoding spaces (U+0020) as `+`, I chose to percent-encode them (i.e. as `%20`). I believe this is still valid `application/x-www-form-urlencoded` (as percentage encoded entitites are allowed), and thus it's less ambiguous to always percent-encode. In this way, whether the server performs `application/x-www-form-urlencoded` decoding or not, it will still result in the same output as we're not using any of the `application/x-www-form-urlencoded` substitution rules (but as of this PR, are now `application/x-www-form-urlencoded` compliant).

Aside: as has been reported elsewhere `application/x-www-form-urlencoded` is fairly poorly [defined](https://www.w3.org/TR/html401/interact/forms.html#h-17.13.4.1), so I think it's safest not to use any of the optional substitution rules (who knows how many OAuth servers would actually decode it correctly if we did).

**Comment by mkujalowicz** [comment]
Thank you for info. I'm sorry for lack of response from my side. I'm still waiting for formal confirmation from my superiors at work about my contribution to the OpenID Foundation codebase. I'll test your changes tomorrow. Thanks again.

**Comment by WilliamDenniss** [comment]
No worries. Thanks again for the great bug report, and I look forward to hearing your results from the testing.

**Comment by mkujalowicz** [comment]
Hi Will,
Everything works great with the fix. The library correctly encodes/decodes tokens.
