### ISSUE TITLE
Apple rejected my submission for UIWebView

### ISSUE THREAD

**Issue by vishnuganta22** [openid/AppAuth-iOS#529]
Pods/Pods/AppAuth/ExternalUserAgent/AppAuth.h has UIWebView

AppAuth Version 1.3.0

**Comment by vishnuganta22** [comment]
![Screenshot 2020-05-05 at 4 20 52 PM](https://user-images.githubusercontent.com/15953004/81058615-6835be00-8eec-11ea-9a88-6181293f69a3.png)

**Comment by chrismash2** [comment]
I can't quite believe that it's this comment that's causing a rejection, surely Apple would be scanning for actual uses of UIWebView...

Either way, this comment is gone in the latest source, but no release yet

**Comment by ProdigalSorc** [comment]
This is the return of Apple Support, mentioning the same line:
![image001](https://user-images.githubusercontent.com/14225522/81810865-1a2b4680-94fa-11ea-8e49-250dfa7663f1.png)

I'm facing this same issue! 
Please, make 1.3.1 version deploy on pod install.

**Comment by ProdigalSorc** [comment]
I could to change podfile, into the projeto, to this:

  pod 'AppAuth', :git => 'https://github.com/openid/AppAuth-iOS.git', :branch => 'master'

Cleanned project e did the `pod update`. 
It finally showes on update:
Installing AppAuth 1.3.1 (was 1.3.0)

I'm facing this problem on TestFlight, with this change, the issue was solved.

**Comment by PrakashMaharjan** [comment]
Apple is rejecting submit..

**Comment by julienbodet** [comment]
Version 1.3.1 is now available with Cocoapods.
