### ISSUE TITLE
How to authenticate without storing cookies in browser

### ISSUE THREAD

**Issue by Guy783** [openid/AppAuth-iOS#530]
Have been trying to build logout feature. Tried to use `EndSessionRequest` to no avail.

Opted to remove Tokens from app. But upon login following logout, cookies remain in browser so the app auths with tokens yet to naturally expire (via cookies in browser).

How can Auth without storing cookies on browser. 

Have been looking around in Issues, there is talk of `SFSafariViewController` with `prefersEphemeralWebBrowserSession`. I've also been reading of using `OIDExternalUserAgent`

Any idea how I could do the above (not store cookies), or logout in such a way that cookies are removed from the browser?

cc @WilliamDenniss

**Comment by Guy783** [comment]
I've sen comment https://github.com/openid/AppAuth-iOS/issues/209#issuecomment-404353236. It's not very to understand how to do this. Would someone be able to provide a swift example, or some documentation please. Thank you.

cc @WilliamDenniss

**Comment by Guy783** [comment]
Ok so using the standard auth methods I updated `OIDExternalUserAgentIOS` in the method `presentExternalUserAgentRequest` , where `ASWebAuthenticationSession` is used to have this line of code `_webAuthenticationVC.prefersEphemeralWebBrowserSession = true;`

`
_webAuthenticationVC = authenticationVC;
            if (@available(iOS 13.0, *)) {
                  _webAuthenticationVC.prefersEphemeralWebBrowserSession = true;
            } else {
                // Fallback on earlier versions
            }
            openedUserAgent = [authenticationVC start];
` 
Would you be able to make this a feature option passed into the parameters such that we can log in using private browsing.

**Comment by julienbodet** [comment]
@Guy783 This was previously discussed in #402. It is preferred to have dedicated user agents for each particular use case instead of making the existant ones customizable for every possible and imaginable use case. The good news is that AppAuth allows to implement your own custom user agent and it's really easy to do. William's [comment](https://github.com/openid/AppAuth-iOS/issues/402#issuecomment-506595068) gives some details on how to do it.

This [section](https://github.com/openid/AppAuth-iOS/issues/402#issuecomment-506595068) of the README is dedicated to Custom User Agents and gives some details about how to use and create them.

**Comment by Guy783** [comment]
Here's a link to an my example for an external agent in swift for anyone who would like a place to start. 
https://gist.github.com/Guy783/446b4921cf0894f031eacbd641122928
