### ISSUE TITLE
Misleading specification

### ISSUE THREAD

**Issue by dizzus** [openid/AppAuth-iOS#69]
README file mentions iOS7 and macOS 10.8 as supported versions.
My configuration is OSX 10.9 with XCode 6.2 (iOS 8.2 SDK installed). 

Since XCode 6.x (and below) doesn't support new Objective C features, such as "nullable",
"__nullable", "NS_ASSUME_NONNULL_BEGIN/END" and NSArray/NSDictionary generics
the project cannot be compiled with this version. Hence the minimum macOS requirement 
should really be 10.10 (which is XCode 7's requirement).

The minimum requirement for iOS should really be iOS 9.x since you cannot
successfully compile the project without iOS 9 SDK installed because of the "SFSafariViewController / SFSafariViewControllerDelegate" dependency.

Cheers, Dmitry.

**Comment by WilliamDenniss** [comment]
We do indeed support iOS 7.0 as a deployment target, but we only support the latest version of the SDK. Your issue relates to the difference between the "deployment target" and "base SDK". The readme and Podspec is referring to the deployment target when it declares iOS 7 support.

It's a lot of work to support old SDKs, for very little gain since people can still target old versions of iOS with the current SDK, thus supporting non-latest SDKs is a non-goal for AppAuth.
