### ISSUE TITLE
Remove offline permission screen

### ISSUE THREAD

**Issue by chamnap** [openid/AppAuth-iOS#70]
I'm a novice ios developer. I would like to remove offline permission screen during authentication from Google. It's a simple application, and I don't need to do anything offline. My users feel weird about this screen. 

The scope I'm using `[OIDScopeOpenID, OIDScopeEmail, OIDScopeProfile]`. I'm using discovery api with `additionalParameters: ["access_type": "online", "prompt": "select_account"])`.

On ruby side, I'm using https://github.com/zquestz/omniauth-google-oauth2/, and it works out of the box with the same scope and same parameters.

Please help me ....

**Comment by ve7jtb** [comment]
Offline access with Google gives the app a refresh token. 

If you don't get one for your app, the access token will expire in an hour and you will need to take the user back to reauthenticate in the custom tab/webview.  We recommend apps use refresh tokens (offline access in google speak) to avoid needlessly re authenticating users.

Are you only authenticating the user once to get the id_token to pass to your back end?
I ask because there are additional verifications of id_tokens that need to be done by the backend if you are using it to protect your apps 3rd party API.

John B.

**Comment by chamnap** [comment]
@ve7jtb, thanks for your reply.

Well, my native app is a hybrid-web app, where I use `wkwebview`, and it just loads a url. Previously, the authentication is done inside that `wkwebview` with `omniauth-google-oauth2`. The thing is that google just deprecated the OAuth authentication inside webview. Therefore, I'm using `AppAuth-iOS` to do google authentication outside webview, in this case, using `SFSafariViewController`. 

Yeah, once when I got the `access_token`, I just direct my `wkwebview` to `/google/oauth2/access_token?access_token=some_value`. Then that `wkwebview` got authenticated (cookie will be expired for a week or so). On the backend side, I fetch information from google about that user, and authenticates him if valid.The next time he opens the app, he will be logged in again, because the wkwebview remembers its cookies, and I don't need to store anything inside the native app.

**Comment by ve7jtb** [comment]
The URI /google/oauth2/access_token?access_token=some_value is on your server, If I understand you.   Your server then gives your app/webview a one week session cookie( I expect that you can extend that as you like as the user interacts with the app).   

How is your backend fetching the information about the user from Google?
Are you using https://www.googleapis.com/oauth2/v3/tokeninfo?access_token=1/fFBGRNJru1FQd44AzqT3Zg

and checking audience and userid or just using it to call the profile?

Are you asking for a id_token and doing anything with that?

I understand why you don't need offline access.

I am trying to understand your use case as we have found serious security issues with some apps trying various shortcuts to get around having there own OAuth server.

Your hybrid app use case is not one we have discussed, so I would like to understand it.

Regards
John B.

**Comment by chamnap** [comment]
Yeah, `/google/oauth2/access_token?access_token=some_value` is on my server. Surely, we can extend more on session cookie.

To fetch information about the user from Google, I use this `https://www.googleapis.com/oauth2/v1/userinfo`. Basically, I just need `uid`, `email`, `profile` on the server, and the native client already sent the scope with that as well, `[OIDScopeOpenID, OIDScopeEmail, OIDScopeProfile]`.

I'm not sure about `id_token`, but the main intention is to get rid of offline access, because this screen doesn't show up previously, and we got complaints from our users as well. They feel like we are doing something secret behind the scene, while we don't do anything.

**Comment by ve7jtb** [comment]
Unfortunately that method of verification leaves any information you have stored for the user wide open to hackers.  

A user of your app going to any other site on the internet where they use google authentication from   the same or any other computer will generate a access token for that site that they can call your  /google/oauth2/access_token?access_token=some_value api with to get a session cookie for the user and get access to your info.

if you are using an access token for this then you are going to need to call both:
https://www.googleapis.com/oauth2/v1/userinfo
https://www.googleapis.com/oauth2/v3/tokeninfo

One for security to see if the token was issued to your client_id and the other to get the additional info.

If you just need the email and uid then you could send the id_token to your backend and validate the signature (it is a JWT) and extract the email, audience(must be your client_id) , and sub(uid).

Other options to consider would be to send the code, and PKCE verifier to your backend and have the backed do the exchange and get get the AT for the user.   That prevents the attack as well.

This google documentation may help
https://developers.google.com/identity/sign-in/web/backend-auth
(Note you can use a JWT library to verify the id_token rather than the google introspection endpoint)

This paper also explains some of the possable exploits if the backend is not careful in how it verifies the AT or id_token  https://www.enisa.europa.eu/publications/info-notes/exploiting-oauth-2-0-protocol-in-mobile-applications

This is a bit outside the scope of AppAuth but we have been debating how we can rase developer awareness on the issues.

Regards
John B.

**Comment by chamnap** [comment]
@ve7jtb, Thanks for your security tips.

Any idea how to remove offline access screen?

**Comment by WilliamDenniss** [comment]
What is the client ID that you're using? If you register as an iOS app, then you shouldn't get the "offline access" screen. That is typically shown for Web based clients, and only when they request a *second* refresh token.

**Comment by chamnap** [comment]
No, it's an ios client.

<img width="685" alt="screen shot 2017-03-06 at 4 03 16 pm" src="https://cloud.githubusercontent.com/assets/407708/23603265/efaa012a-0286-11e7-847b-7e5b019a9e80.png">

**Comment by rujoota** [comment]
Hi @chamnap ,

Were you able to solve the problem?

I am looking for similar results where I want to have Google cookies and I know that using either uiwebview or wkwebview will give me access to those cookies. I also need some basic user info to store in my database and enable 'sign in with Google' functionality for users. Google's sign in SDK helps but it does not provide me with cookie information. (I do not have omni-auth server separately).

**Comment by chamnap** [comment]
@rujoota, I could not solve the problem. I believe the library doesn't something when fetching access token (a refresh token). That's why Google thinks we store it for later usage.
