### ISSUE TITLE
Get username during authentication process

### ISSUE THREAD

**Issue by VicoliGiordano** [openid/AppAuth-iOS#752]
Hi,

Is there a way to get the username the user authenticates with?

Thanks,
Giordano

**Comment by holgerde** [comment]
I don't think that's possible, because then there would also be a way to get the password. The whole point of ASWebAuthenticationSession (which is used under the hood) is to provide a sandbox to shield the authentication process from the app.

Also, a particular authentication method might not even be based on a username but something else to identify the user.

**Comment by dermaaarkus** [comment]
After successfully authenticated you can request the user information with the given tokens.
That's what I do in my app and it works perfectly.
