### ISSUE TITLE
XCode 14.3 Beta cant archieve app because of AppAuth.framework pod

### ISSUE THREAD

**Issue by christopherarm** [openid/AppAuth-iOS#759]
**Describe the bug**

I recently installed XCode 14.3 Beta to build my Apps for iOS 16.4. I use flutter for development.
Now i get this error when i try to build the ipa or archieve the app via XCode:

`mkdir -p /Users/chris/Library/Developer/Xcode/DerivedData/Runner-hjyvfkwvhrjdsnelaqvdpdxpoyit/Build/Intermediates.noindex/ArchiveIntermediates/Runner/BuildProductsPath/Release-iphoneos/Runner.app/Frameworks
Symlinked...
rsync --delete -av --filter P .*.?????? --links --filter "- CVS/" --filter "- .svn/" --filter "- .git/" --filter "- .hg/" --filter "- Headers" --filter "- PrivateHeaders" --filter "- Modules" "../../../IntermediateBuildFilesPath/UninstalledProducts/iphoneos/AppAuth.framework" "/Users/chris/Library/Developer/Xcode/DerivedData/Runner-hjyvfkwvhrjdsnelaqvdpdxpoyit/Build/Intermediates.noindex/ArchiveIntermediates/Runner/InstallationBuildProductsLocation/Applications/Runner.app/Frameworks"
building file list ... rsync: link_stat "/Users/chris/Downloads/tuduu_app/ios/../../../IntermediateBuildFilesPath/UninstalledProducts/iphoneos/AppAuth.framework" failed: No such file or directory (2)
done`

**To Reproduce**
1. Create flutter project with XCode 14.3 Beta installed
2. Run 'flutter build ipa' or run Product>Archieve in XCode

**Expected behavior**
The build should run fine and generate the ipa file.

**Screenshots**
![image](https://user-images.githubusercontent.com/90921702/228348666-5ba5a706-88a4-4a69-9398-34ab86a15044.png)

**Environment**
- Device: [ iPhone 12 ]
- OS: [ iOS 16.4 Beta ]
- XCode 13.4 Beta

**Comment by junytse** [comment]
I meet a similar issue when using `carthage bootstrap` with Xcode 14.3. The log reports a deployment target warning and an error about missing `...`:

```
ld: file not found: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/arc/libarclite_iphoneos.a
clang: error: linker command failed with exit code 1 (use -v to see invocation)

... Carthage/Checkouts/AppAuth-iOS/AppAuth.xcodeproj: warning: The iOS deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 11.0 to 16.4.99. (in target 'AppAuth_iOS' from project 'AppAuth')
```

I manually updated the deployment targets of AppAuth_iOS and AppAuthCore build targets to 9.0 to resolve the build failure.

**Comment by dawiddszewczyk** [comment]
This same error

**Comment by kennir** [comment]
I have the same problem

**Comment by szastavnyy** [comment]
Solution with -f helped me:

https://developer.apple.com/forums/thread/725230

**Comment by dawiddszewczyk** [comment]
For me downgrade to 14.2 for now works

**Comment by paulb777** [comment]
The podspec should be bumped to a minimum of at least iOS 9.0 and comparable version for other platforms to work out of the box with Xcode 14.3

**Comment by mdmathias** [comment]
I've drafted #761 to address this issue. The PR is in draft for now while I download Xcode 14.3 to test.

**Comment by mdmathias** [comment]
Wanted to follow up that the issue here seems to track two things: 1) a [CocoaPods bug](https://github.com/CocoaPods/CocoaPods/issues/11808) that I don't think we can solve directly here, and 2) a build issue highlighted in https://github.com/openid/AppAuth-iOS/issues/759#issuecomment-1487880042.

#761 addresses the second of the two above. I was able to build and run a test app in Xcode 14.3 with the `podfile` depending on this branch: `pod 'AppAuth', :git => 'https://github.com/openid/AppAuth-iOS.git', :branch => 'mdmathias/fix-for-xcode-143'`.

The first issue concerning archiving a CocoaPods app is still present. There are a few workarounds for that one. See the discussion thread on the CocoaPods issue above, or take a look at some [examples from flutter](https://github.com/flutter/flutter/issues/124340#issuecomment-1499581283).

Last, it seems like there was a [PR fixing the issue for Xcode 14.3 in CocoaPods](https://github.com/CocoaPods/CocoaPods/pull/11828).

**Comment by Sougata6** [comment]
"ENT_TARGET' is set to 10.0, but the range of supported deployment target versions is 11.0 to 16.4.99. (in target 'FirebaseFirestore' from project 'Pods')
** BUILD FAILED **


The following build commands failed:
        Ld /Users/ayansaha/Projects/Ingredion/IngredionTapiocaPartner/platforms/ios/build/emulator/AppAuth.framework/AppAuth normal (in target 'AppAuth' from project 'Pods')
(1 failure)
xcodebuild: Command failed with exit code 65
npm ERR! code ELIFECYCLE
npm ERR! errno 65
npm ERR! itpa-frontend@1.8.8 ios-build-uat: `npm run build-mobile-uat && cordova build ios`
npm ERR! Exit status 65
npm ERR! 
npm ERR! Failed at the itpa-frontend@1.8.8 ios-build-uat script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/ayansaha/.npm/_logs/2023-04-08T18_08_00_560Z-debug.log"

I also got this issue after updating to xcode 14.3

**Comment by mdmathias** [comment]
@Sougata6 please refer to https://github.com/openid/AppAuth-iOS/issues/759#issuecomment-1500570385. It describes your options if the error is related to archiving or building.

Additionally, AppAuth-iOS 1.6.1 [is available on CocoaPods](https://cocoapods.org/pods/AppAuth). If the issue is related to building, then this should help.
