### ISSUE TITLE
For Xcode 14.3, Minimum deployment target should be least 9.0

### ISSUE THREAD

**Issue by meetmandar** [openid/AppAuth-iOS#765]
**Describe the bug**
For Xcode 14.3, Minimum deployment target should be least 9.0

**To Reproduce**
1. Open latest code in Xcode
2. Select AppAuth_iOS from targets
3. Go to build settings 
4. Locate IPHONEOS_DEPLOYMENT_TARGET, value is set to 8.0

**Expected behavior**
IPHONEOS_DEPLOYMENT_TARGET, value should be minimum 9.0

**Environment**
- Xcode 14.3

**Additional context**

**Comment by mdmathias** [comment]
As an example, if I use one of the [sample Apps from GoogleSignIn-iOS](https://github.com/google/GoogleSignIn-iOS/tree/main/Samples/Swift/DaysUntilBirthday), which depends on AppAuth-iOS, I see the below.

![image](https://user-images.githubusercontent.com/4029922/232101984-58269ef9-9dab-4b7f-ab99-de4c8f486959.png)

**Comment by meetmandar** [comment]
It is not fixed AppAuth_iOS target

<img width="835" alt="Screenshot 2023-04-15 at 12 31 28 AM" src="https://user-images.githubusercontent.com/13957158/232133720-80ce92cf-e607-48bd-9731-977d7a21135f.png">

**Comment by mdmathias** [comment]
Would you mind sharing how you're generating this project? Also, I don't know what AppAuth_iOS is. Related, are you sure that you're using the latest tagged release (1.6.1)?

**Comment by Rajasekar-C** [comment]
> Would you mind sharing how you're generating this project? Also, I don't know what AppAuth_iOS is. Related, are you sure that you're using the latest tagged release (1.6.1)?

@mdmathias Our app depends on the AppAuth_iOS framework, We are not able to build it into Xcode 14.3 as it has iOS deployment target 8.0. I hope you know that a minimum deployment target should be minimum 9.0 for Xcode 14.3.

Steps to re-create:
1. Download the [Source code(zip)](https://github.com/openid/AppAuth-iOS/archive/refs/tags/1.6.1.zip) by manually or via Carthage from (https://github.com/openid/AppAuth-iOS/releases/tag/1.6.1)
2. Extract it and open AppAuth.xcodeproj
3. There are 18 targets in this, Few of them have 9.0 and few of them are not (e.g. AppAuth_iOS, AppAuthCore)
4. If you compile AppAuth_iOS in Xcode 14.3, it will fail because it has a minimum deployment target of 9.0.

<img width="1226" alt="Screenshot 2023-04-17 at 11 36 07 AM" src="https://user-images.githubusercontent.com/14174446/232399702-3dfac2b2-e95c-44ea-aa37-5650b7dd8f1e.png">

We request you to update the deployment target to 9.0 for the missing targets, as you have updated the others.

**Comment by mdmathias** [comment]
Thanks for the additional detail. I've reopened this issue and have a PR drafted. I will follow up with more soon after I investigate this a little more. Thanks for your understanding.

**Comment by tiwariammit** [comment]
Anyone fixed how to do logout properly?
