### ISSUE TITLE
AppAuth/Resources/PrivacyInfo.xcprivacy not copied into Pod

### ISSUE THREAD

**Issue by mmartinelliGC** [openid/AppAuth-iOS#848]
**Describe the bug**
When importing AppAuth via CocoaPods, the PrivacyInfo.xcprivacy is not copied into the Pods directory.

**To Reproduce**
1. Add AppAuth @1.7.4 to a test project via cocoapods
2. Observe Pods/AppAuth/Sources/AppAuth and see that the Resources folder is not present
3. Compare this to Pods/AppAuth/Sources/AppAuthCore and see that the Resources folder exists and includes the PrivacyInfo.xcprivacy file

**Expected behavior**
Pods/Sources/AppAuth/Resources exists with PrivacyInfo.xcprivacy copied to it

**Screenshots**
<img width="514" alt="Screenshot 2024-04-16 at 1 13 18 PM" src="https://github.com/openid/AppAuth-iOS/assets/88156772/836222e0-cdb1-4657-8e34-20234aa05ee1">

**Environment**
Xcode 15.3, macOS 14.4
Building for iOS

**Additional context**
Seems similar to #832. I was able to resolve this by modifying AppAuth.podspec, adding the following:

`s.resource_bundles = {
    "AppAuth_Privacy" => ["Sources/AppAuth/Resources/PrivacyInfo.xcprivacy"]
  }`

**Comment by mdmathias** [comment]
This is a little different than #832 since the privacy manifest wasn't being picked up at all under SPM. IIRC, the reason I put a `Resources/` folder (with a privacy manifest) under each target in the `Package.swift` was to ensure that there was a privacy manifest for each target. In retrospect, this is likely not necessary given what I lay out below (namely, that each product/target in `Package.swift` depends upon "AppAuthCore," which [does supply a manifest](https://github.com/openid/AppAuth-iOS/blob/master/Package.swift#L31-L68)).

In the case here, the ['Core' subspec](https://github.com/openid/AppAuth-iOS/blob/master/AppAuth.podspec#L49) is pulling in its `PrivacyInfo.xcprivacy` as you show above. Since every subspec depends upon the 'Core' subspec, and since ['Core' is a default subspec](https://github.com/openid/AppAuth-iOS/blob/master/AppAuth.podspec#L80), the privacy manifest will always be present in builds using CocoaPods [1]. Moreover, AppAuth is only usable via code organized and shared via these subspecs (in the case of CocoaPods).

Given this, my thinking was that we did not need each subspec to list its own privacy manifest (and we did not need one at the top level) since they would not add anything different.

I'm going to close this for now, but please let me know if you believe this will cause app review problems for you.

[1] For example, if the below was your `Podfile` definition, you would still pull in the 'Core' subspec and have the privacy manifest copied into your bundle.

```
project 'PrivMan.xcodeproj'
use_frameworks! :linkage => :static

target 'PrivMan' do
  pod 'AppAuth/TV'
  platform :tvos, '16.0'
end
```

**Comment by mmartinelliGC** [comment]
Thank you for the clarification, will reach back out if we run into any problems with app review

**Comment by mdmathias** [comment]
Absolutely. Please let us know if there is problem and I will make sure to get a release out ASAP.
