### ISSUE TITLE
rebeccamccarty299@yahoo.com

### ISSUE THREAD

**Issue by rebeccamccarty** [openid/AppAuth-iOS#857]
**Is your feature request related to a problem you're having? Please describe.**
A clear and concise description of what the problem is.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by TizzumT84** [comment]
Someone is using this to hack apps on my phone. I never created the account Sent from my iPhoneOn May 6, 2024, at 2:55 PM, rebeccamccarty ***@***.***> wrote:﻿
Is your feature request related to a problem you're having? Please describe.
A clear and concise description of what the problem is.
Describe the solution you'd like
A clear and concise description of what you want to happen.
Describe alternatives you've considered
A clear and concise description of any alternative solutions or features you've considered.
Additional context
Add any other context or screenshots about the feature request here.

**Comment by mingyokim** [comment]
Closing due to lack of information.
