### ISSUE TITLE
iOS Keychain Integration

### ISSUE THREAD

**Issue by arkuhn** [openid/AppAuth-iOS#91]
Are there any existing plans to include some form of iOS Keychain wrapper with this library? It seems the only secure option (as opposed to NSUserDefaults), and fairly common procedure for persisting tokens.

**Comment by WilliamDenniss** [comment]
When we architected AppAuth, we decided that the _storage_ of tokens was out of scope – something that would be implemented either in a higher layer library, or in the application itself. _Serialization_ is in scope though, all AppAuth models implement `NSSecureCoding`, so you can easily use AppAuth with the Keychain wrapper of your choice by serializing to and from `NSData`.

The benefit of this layer separation is that AppAuth operates hermetically. It can't accidentally modify state that your app depends on, since you are responsible for maintaining that state.

Google's [iOS authentication library](https://github.com/google/GTMAppAuth) which is a layer above (and dependant on) AppAuth does exactly this, by providing a KeyChain wrapper.  If you need a library which is more opinionated about token storage, you can potentially use that one (it's open source, and works with _all_ providers, not just Google).

**Comment by arkuhn** [comment]
Thanks for the hasty response and nice recommendation. I understand that design choice. Thanks again for the help!
